#!/bin/sh
set -e
cd "${APPDIR}"
export PATH="${APPDIR}/usr/bin/${PATH:+:$PATH}"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${APPDIR}/usr/share/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
export DATA_FILE_PATH="${APPDIR}/usr/share/assets/Data"
EXEC="$(grep -e '^Exec=.*' "${APPDIR}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)"
exec "${APPDIR}/usr/bin/${EXEC}" "$@"
