name: Package

on: [workflow_dispatch]

jobs:
  package-macos:
    runs-on: macos-14
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Compile macOS universal app
        run: ./build-mac-app.sh

      - uses: actions/upload-artifact@v6
        with:
          name: mac-build-universal
          path: build/Reckless-Drivin-*-mac.dmg

  package-linux:
    runs-on: ${{ matrix.platform.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: x86_64, os: ubuntu-22.04 }
          - { name: aarch64, os: ubuntu-22.04-arm }

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Compile Linux ${{ matrix.platform.name }} app
        run: |
          sudo apt update
          sudo apt install -y desktop-file-utils libsdl2-dev
          ./build-linux-app.sh

      - uses: actions/upload-artifact@v6
        with:
          name: linux-build-${{ matrix.platform.name }}
          path: build/Reckless-Drivin-*-linux-${{ matrix.platform.name }}.AppImage

  package-windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Install SDL2 via vcpkg
        run: vcpkg install sdl2:x64-windows

      - name: Build
        run: |
          cmake -B build -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
          cmake --build build --config Release

      - name: Package
        run: |
          $version = (Select-String -Path CMakeLists.txt -Pattern 'VERSION (\d+\.\d+\.\d+)').Matches.Groups[1].Value
          mkdir package
          cp build/Release/RecklessDrivin.exe package/
          cp build/Release/Data package/
          cp build/Release/*.dll package/
          if (!(Test-Path package/SDL2.dll)) {
              cp "$env:VCPKG_INSTALLATION_ROOT/installed/x64-windows/bin/SDL2.dll" package/
          }
          Compress-Archive -Path package/* -DestinationPath "build/Reckless-Drivin-$version-windows-x64.zip"

      - uses: actions/upload-artifact@v6
        with:
          name: windows-build-x64
          path: build/Reckless-Drivin-*-windows-x64.zip
